import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Form, FormControl, Button } from 'react-bootstrap';
import Shops from '../components/Shops';

const Home: NextPage = () => {
	const [click, setClick] = useState(false);
	const [searchQuery, setSearchQuery] = useState('');
	const handleSearch = (e: any) => {
		e.preventDefault()
		setClick(true);
	};
	const onInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		e.preventDefault();
		setSearchQuery(e.target.value);
	};
	const resetClickVar = (val: boolean) =>
	{
		setClick(val)
	}
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Form className="d-flex" onSubmit={handleSearch}>
					<FormControl
						type="search"
						placeholder="Search"
						className="me-2"
						aria-label="Search"
						onChange={onInputChange}
					/>
					<Button variant="outline-success" onClick={handleSearch}>
						Search
					</Button>
				</Form>
				<h2>Shops</h2>
				<Shops clicked={click} searchQuery={searchQuery} resetSearch={resetClickVar}/>
			</main>
		</div>
	);
};

export default Home;
